name: CI
on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
      - "release/**"
jobs:
  build_and_test:
    name: build and test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and test
        run: |
          bundle install

          set -o pipefail && xcodebuild test -project Password-Generator.xcodeproj -scheme "Password-Generator (iOS)" \
            -destination "platform=iOS Simulator,name=iPhone 13 Pro Max" | bundle exec xcpretty || exit 1
