name: CI
on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
      - "release/**"
jobs:
  installDependencies:
    name: install dependencies
    runs-on: macos-latest
    steps:
      - name: gem bundles
        run: |
          bundle install
  buildAndTest:
    name: build and test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and Test
        run: |
          set -o pipefail && xcodebuild test -project Password-Generator.xcodeproj -scheme "Password-Generator (iOS)" \
          -destination "platform=iOS Simulator,name=iPhone 13 Pro Max" | bundle exec xcpretty || exit 1
