name: CI
on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
      - "release/**"
jobs:
  build_and_test:
    name: build and test
    runs-on: macos-11
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Git - Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup - Xcode
        run: sudo xcode-select -s /Applications/Xcode_13.app

      - name: Setup - Ruby and bundler dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Test
        run: |
          set -o pipefail && xcodebuild test -project Password-Generator.xcodeproj -scheme "Password-Generator (iOS)" \
            -destination "platform=iOS Simulator,name=iPhone 12 Pro Max" | bundle exec xcpretty || exit 1
