name: CI
on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
      - "release/**"
jobs:
  test:
    name: Test
    timeout-minutes: 15
    runs-on: macos-latest
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Git - Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup - Xcode
        run: |
          sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer
        # uses: maxim-lobanov/setup-xcode@v1
        # with:
        #   xcode-version: "12.4"

      - name: Setup - Ruby and bundler dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Test
        run: |
          set -o pipefail && xcodebuild test -project Password-Generator.xcodeproj -scheme "Password-Generator (iOS)" \
            -destination "platform=iOS Simulator,name=iPhone 12 Pro Max" | bundle exec xcpretty || exit 1
